name: CI


on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 15 * *'


jobs:
  ci:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configure
        run: npx --package mini-cross@0.15.2 mc --no-tty _ cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang

      - name: Build
        run: npx --package mini-cross@0.15.2 mc --no-tty _ cmake --build build

